jhipster/jhipster-registry

Dockerfile
Here is a sample docker-compose file to demonstrate the feature:
```
jhipster-registry:
container_name: jhipster-registry
build: ./jhipster-registry/
environment:
- "SPRING_PROFILES=dev,native"
ports:
- "8761:8761"
volumes:
- ./central-config:/central-config
```
I have set the default to prod. I have done it because since #8 we use the `central-config` folder in  https://github.com/jhipster/jhipster-registry as the config source. Also I read somewhere that the native profile was bad because it could not "cache" the configuration and was forced to read it from disk every time it needed it. I'm not sure if it still does that but anyway the git config is the way to go.
=> allow passing the profile to the docker image 

pom.xml, src/main/docker/dev/Dockerfile
I followed this [spring guide](https://spring.io/guides/gs/spring-boot-docker/), as I already do :)
- type `mvn package docker:build` to package + generate a new Docker image
- the image created is : **jhipster/jhipster-registry:dev**
- if you don't like the name or the tag, simply modify it in pom.xml
=> Allow maven to containerize the application

Dockerfile, pom.xml, src/main/docker/dev/Dockerfile
To be consistent with https://github.com/jhipster/generator-jhipster/pull/3085
Use directly openjdk8 package instead of non official link
The issue https://github.com/jhipster/jhipster-registry/issues/16 should be resolved before merging this.
=> Use openjdk8 and remove non official link

central-config/application.yml
Enable the yaml file to be correctly displayed in browsers.
=> add trailing slash to configserver.status

Dockerfile
The default spring.profiles.active is prod
It can now be overwritten in docker-compose files, by environment variables
Fix https://github.com/jhipster/generator-jhipster/issues/3228
=> Fix default spring profiles active, which can now be overwritten

pom.xml
#37 Fixes the build to allow using the `dev` profile when running locally.
=> Add build step to use dev profile

package.json
Fix https://github.com/jhipster/jhipster-registry/issues/61
=> [develop] Upgrade gulp-angular-templatecache from 1.8.0 to 1.9.0

app.json
People seem to have trouble finding the autogenerated password. This will make it easier for them to log in once they've deployed.
=> Use a custom password for Heroku instead of the autogenerated

app.json
Set buildpack explicitly to avoid this warning:
```
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
```
Also improve password description, as it must be at least 5 characters.
=> Updated app.json

src/main/webapp/app/config/config.controller.js
Application name appeared in lowercase even with uppercase characters. Couldn't display configuration file with a wrong application name.
=> fix autocomplete for services in configuration screen

src/main/webapp/app/ssh/ssh.html
When the GIT_URI begins with `ssh:` as in the example, I get `com.jcraft.jsch.JSchException: Auth fail` even if the repository is public.
I also updated the example to use an actual example repository and folder path.
=> fix ssh git setup example

pom.xml, src/main/java/io/github/jhipster/registry/config/WebConfigurer.java, src/main/resources/config/application-dev.yml, src/main/resources/config/application-peer1.yml, src/main/resources/config/application-peer2.yml, src/main/resources/config/application-prod.yml
I'm changing the `eureka.server.enable-self-preservation` to `false`, so the evict task will unregister the service properly.
Fix https://github.com/jhipster/generator-jhipster/issues/3654
Note: I did a rebase on the develop branch too, so there are additional commits
=> [develop] Change enable-self-preservation to false

src/main/java/io/github/jhipster/registry/service/ZuulUpdaterService.java, src/main/webapp/app/admin/configuration/configuration.component.ts, src/main/webapp/app/admin/health/health.component.ts, src/main/webapp/app/admin/logs/logs.component.html, src/main/webapp/app/admin/logs/logs.component.ts, src/main/webapp/app/admin/metrics/metrics.component.html, src/main/webapp/app/admin/metrics/metrics.component.ts, src/main/webapp/app/shared/auth/state-storage.service.ts, src/main/webapp/app/shared/routes/route-selector.component.html, src/main/webapp/app/shared/routes/route-selector.component.scss, src/main/webapp/app/shared/routes/route-selector.component.ts, src/main/webapp/app/shared/routes/routes.service.ts
In accordance with @jdubois, I added two new things.
_Of course, as I usually do, a gif to show you :_
<br><br>
So, you can choose a particular instance (and/or a refresh time) in a admin page, and go to another page, these choices are stored.
(routes.services.ts, the 4 admin html pages, ZuulUpdaterService.java). 
In particular to protect when a microservice/gateway fails (even if there are sometimes little problems due to Eureka, like microservices/gateways that are down but that have a 'UP' status...).
<br>
Tell me if you have some questions/suggestions/...
=> Add refresh timer, memorizes choices and avoid some inconsistencies

package.json, pom.xml
This allows platforms like Heroku to skip tests during deployment.
=> Move webpack tests to test phase

Dockerfile
Sorry for other PR https://github.com/jhipster/jhipster-registry/pull/119 from @PierreBesson 
This PR will fix the build for develop branch.
@jdubois :
- the current tests failed (yarn test -> that's why the Dockerfile here will skipTests)
- so you need to merge https://github.com/jhipster/jhipster-registry/pull/127 first
- the global size will change: from 128 MB to 305 MB (because of openjdk:8 instead of alpine)
For people who want to test:
- build: `docker build -t jhipster/jhipster-registry:local .`
- run: `docker run --rm --name registry -p 8761:8761 -e SPRING_PROFILES_ACTIVE=dev,native -e JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET=toto jhipster/jhipster-registry:local`
=> [develop] Fix Docker build with Angular

src/main/webapp/app/registry/config/config.component.html, src/main/webapp/app/registry/config/config.component.ts, src/main/webapp/app/shared/routes/route-selector.component.ts, webpack/webpack.dev.js
Related to #132 :
- Fixed red status instead green
- Added config path to webpack, and update the "form" part (in particular the old typeahead who was not working)
__Note__ : I've tried to use the ng-typeahead, but I always have a `"Cannot read property 'lift' of undefined"` error (maybe in BETA) so before the Registry release, I prefer to use a simple select.
=> Fix #132 Red Starting status & spring cloud config page

app.json
This will show the JHipster logo on the Heroku button deploy page.
=> Added logo to app.json

src/main/webapp/app/admin/configuration/configuration.component.ts, src/main/webapp/app/admin/metrics/metrics.component.html
- This commit fixes a bug on the Metrics page.
If you have selected a refresh time on the Metrics page, when data are reloaded, your cursor goes back to the top of the page, due to some misplaced "ngIf".
So, if you select "5 seconds", it's not possible to correctly scroll on this page.
<br>
- Moreover, I added a little patch on the configuration component (to follow other admin components).
=> Fixed Metrics page that reload the entire content

src/main/java/io/github/jhipster/registry/web/rest/ProfileInfoResource.java, src/main/resources/config/bootstrap-prod.yml, src/main/resources/config/bootstrap.yml
The ProfileInfo resource doesn't return the config's git information or search paths, they currently appear blank.   This PR returns to the pre v3 behavior
=> properly display config git repo and search locations

package.json, pom.xml, src/main/resources/config/bootstrap-prod.yml, src/main/resources/config/bootstrap.yml
Currently
`target/jhipster-registry-v3.1.0.war --spring.profiles.active=dev` doesn't start the native profile. This PR fixes that.
=> Fix bootstrap spring profiles

.travis.yml, Dockerfile
Following the comment here https://github.com/docker/hub-feedback/issues/1039#issuecomment-324020345 : Docker Hub supports multi stage builds with the version 17.06
So it should reduce the docker image size from 352 MB to 113 MB.
@PierreBesson : can you review and test this ?
=> docker: use multi-stage builds to reduce image size

Dockerfile
Fix #189  allow openshift to run the image as non root.
=> Create /target directory and give rights to it

pom.xml
Eclipse marks package-info as duplicate when using eclipse.
Using this configuration fixes the issue
=> Avoids package-info.java erros in Eclipse

pom.xml
Revert to an old version of the config server which doesn't have two endpoints differing only by media type.
This is not ideal, but it's better to downgrade only the config server on an old version rather than downgrade the whole release train to Camden.
=> fix spring cloud config server version to 1.2.3.RELEASE

src/main/java/io/github/jhipster/registry/config/OAuth2SsoConfiguration.java
This PR makes OAuth2SsoConfiguration secure the same endpoints as OAuth2SecurityConfiguration.  When using the `oauth2` profile, you can currently access several api, eureka, and management endpoints without authenticating.  Because of `/api/account` being open, on the initial visit to the registry URL the page shows as if you are signed in as `anonymousUser` like below:
=> secure api endpoints when using OIDC

.travis.yml
>Executing docker install script, commit: 1d31602
Warning: the "docker" command appears to already exist on this system.
If you already have Docker installed, this script can cause trouble, which is
why we're displaying this warning and provide the opportunity to cancel the
installation.
https://travis-ci.org/jhipster/jhipster-registry/builds/324840407#L522-L527
=> remove double docker install on travis

Dockerfile, pom.xml
I was having issues building locally with `mvn -Pwebpack,dev` as I used Node v8 (LTS) when running `yarn install`. Then when I ran `mvn -Pwebpack,dev` on the registry, it crashed telling me to rebuild node-sass for Node v6.  
This does not happen for the `prod` profile because it runs `yarn --force` which rebuilds node dependencies with the node version specified in the pom.xml.
=> update node and yarn versions to match generator-jhipster

pom.xml
I also remove the spring-cloud-starter-netflix-spectator dependencies, as it seems not be used
=> [develop] upgrade to Spring Boot 2.0.0.RELEASE

src/main/webapp/swagger-ui/index.html
Currently, the `index.html` page for Swagger is specific to JWT.
In these changes, it will call `api/profile-info` to know which profile is used, then it will add api key authorisation, according to the profile: oauth2 or default (JWT) :
https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/src/main/webapp/swagger-ui/index.html.ejs#L104-L122
_____
=> [develop] Fix Swagger for OAuth2

src/main/java/io/github/jhipster/registry/config/OAuth2SsoConfiguration.java
The current issue is to access to admin page, with OAuth2 microservices. See the screenshots below.
I fix it by using the similar code for [OAuth2SsoConfiguration.java](https://github.com/jhipster/generator-jhipster/blame/master/generators/server/templates/src/main/java/package/config/OAuth2SsoConfiguration.java.ejs) in generator-jhipster
Maybe @ruddell or @mraible you can have a look ?
_____
=> [develop] Fix Admin pages for OAuth2

pom.xml, src/main/java/io/github/jhipster/registry/config/LoggingConfiguration.java
Current metrics log make console of registry very hard to read another log, so only forward metric log to logstash, not log metrics to console. This make easier when need to check registry error.
=> Only forward metric log to logstash

package.json
My JHipster Registry deploys are failing with Node 10+. If there is a way to say that you want the latest LTS version of node, that would probably be better, but I don't know of such a mechanism.
I've also added a Yarn engine version to ensure it aligns with what's in `pom.xml`.
=> Set node and yarn version in package.json engines

Dockerfile, Procfile, src/main/java/io/github/jhipster/registry/JHipsterRegistryApp.java, src/main/java/io/github/jhipster/registry/config/ConfigServerConfig.java, src/main/java/io/github/jhipster/registry/config/NativeRepositoryConfiguration.java, src/main/java/io/github/jhipster/registry/web/rest/ProfileInfoResource.java, src/main/resources/config/bootstrap-git.yml, src/main/resources/config/bootstrap-prod.yml, src/main/resources/config/bootstrap.yml, src/main/webapp/app/layouts/profiles/profile-info.model.ts, src/main/webapp/app/layouts/profiles/profile.service.ts, src/main/webapp/app/registry/config/config.component.html, src/main/webapp/app/registry/config/config.component.ts, src/main/webapp/app/registry/registry.module.ts
Fix https://github.com/jhipster/jhipster-registry/issues/281
Use the new composite feature of the config server. This allow us to remove the confusing native profile and be able to define several sources at once.
This also fixes the but with the bootstrap + native.
=> switch to composite mode for defining the configserver sources

src/main/java/io/github/jhipster/registry/config/MetricsConfiguration.java
The `MetricsMarkerLogbackFilter` will set a `OnMarkerEvaluator` to filter out all the log marked with "metric".
In order to make the above filter work, we need to set the "marker" for all metric log.
=> fix issue with MetricsMarkerLogbackFilter

src/main/webapp/app/registry/encryption/encryption.component.ts
The {cipher} marker needs to be stripped before passing the
encrypted value to the decryption endpoint
The spring-cloud-config docs also do not use the `{cipher}` part. But I think its really helpful you are appending it to the encrypted value (to allow copy and pasting it into configs)
Reproduce
```
curl localhost:8761/config/encrypt -d mysecret -u admin:admin
```
```
curl localhost:8761/config/decrypt -d $ENCRYPTED_VALUE -u admin:admin
```
works fine
```
curl localhost:8761/config/decrypt -d {cipher}$ENCRYPTED_VALUE -u admin:admin
```
leads to
```json
{
"description" : "Text not encrypted with this key",
"status" : "INVALID"
}
```
=> Fix decryption in Encryption UI

src/main/resources/config/application.yml
Since the migration to Spring Boot 2, we got a lot of error with this stack.
It is to reduce its.
```
2018-10-10 12:36:43.862 ERROR 1 --- [ster-registry-8] c.n.e.cluster.ReplicationTaskProcessor   : It seems to be a socket read timeout exception, it will retry later. if it continues to happen and some eureka node occupied all the cpu time, you should set property 'eureka.server.peer-node-read-timeout-ms' to a bigger value
com.sun.jersey.api.client.ClientHandlerException: java.net.SocketTimeoutException: Read timed out
at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
at com.netflix.eureka.cluster.DynamicGZIPContentEncodingFilter.handle(DynamicGZIPContentEncodingFilter.java:48)
at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(Eurek …
```
=> Increase peer node read timeout

src/main/webapp/app/home/home.component.ts
After login, the refresh button doesn't work because there is no subscription for refreshService.
You need to change page and go back home to use this refresh button.
This PR solves it.
_____
=> Fix refresh at 1st display

Procfile, app.json
This change uses the [JHipster Registry Buildpack](https://github.com/jkutner/jhipster-registry-buildpack) to download and install a precompiled version of the JHipster Registry (instead of buildpack from source).
Building from source takes a long time, and only supports the default Github branch. Users probably don't want to deploy the latest code, but a stable version instead.
Deployment still works by clicking the "Deploy to Heroku" button in the README (i.e. no difference to user experience or docs).
/cc @mraible 
We shouldn't use the Github URL to my custom buildpack. Instead we should adopt one of the following:
* Move the [JHipster Registry Buildpack](https://github.com/jkutner/jhipster-registry-buildpack) into the [jhipster Github org](https://github.com/jhipster/).
* Move the …
=> Updated app.json to use jhipster registry buildpack

src/main/webapp/app/shared/refresh/refresh-selector.component.html, src/main/webapp/app/shared/refresh/refresh-selector.component.scss
This is a little UX feature I was thinking about since we have the auto reload option. I found that it is not comfortable to go into the refresh drop down every time I want to refresh manually, even if a auto-refresh is running. So I moved from this
to this
=> extracts the 'refresh now' button on top

src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java
**Overview of the Issue**
If you make a request using basic auth, it adds a header like `Authorization: Basic YWRtaW46pWRtaW4=`.  There is an [OAuth2 config](https://github.com/jhipster/jhipster-registry/blob/66e30324d479b8f2c6c6070f12dcf298b633ff4c/src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java#L58-L83) that is used when there is an `Authorization` header, and in that config the `/eureka` and `/config` paths are not secured.  A plain request won't be able to access the endpoints, but one using any basic auth credentials works.
**Steps to Reproduce**
Start the registry with the `oauth2` profile (I just add it in `bootstrap.yml`)
`curl -v http://this-should:not-work@localhost:8761/eureka/apps`
Originally reported here: …
=> secure eureka/config paths for oauth2 request with auth header

src/main/java/io/github/jhipster/registry/config/JWTSecurityConfiguration.java, src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java, src/main/java/io/github/jhipster/registry/config/OAuth2SsoConfiguration.java, src/main/java/io/github/jhipster/registry/config/WebConfigurer.java
- Fix #246 
- Tested with dummy client and fix seems to work.
- Configure fallback URL with default deny all CORS configuration. This would guard against any URL not explicitly allowed and pre-flight requests would correctly receive 403 status with 'Invalid CORS request' as response
=> Enable CORS on eureka endpoints

src/main/java/io/github/jhipster/registry/config/ApplicationProperties.java, src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java, src/main/resources/config/application-oauth2.yml
Different OAuth2 servers use different attributes. This change allow to user customize attributes name for `principal` and `authorities`.
=> move oauth2 attributes to config

src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java
Fix basic authentication issue. Default behavior is to conditionally create the `InMemoryUserDetailsManager` bean in absence of `ClientRegistrationRepository` bean.
=> Fix basic auth login issue

app.json
This environment variable is used by the Heroku buildpack that downloads a pre-compiled version of the registry. According to this repo's [Releases](https://github.com/jhipster/jhipster-registry/releases), 5.0.2 is the latest.
=> Update app.json to 5.0.2 jhipster registry version

src/main/webapp/app/registry/replicas/replicas.service.ts
amend findAll() method in webapp/app/registry/replicas/replicas.service.ts to include the parameter { observe: 'response' }
Fix #409
=> fix for replicas display page

src/main/webapp/app/registry/replicas/replicas.component.html
I'm changing the eureka.server.enable-self-preservation to false in replica documentation in order to reflect the values in the different application YML files.
Fix jhipster/jhipster-registry/issues/426
=> Fix enable-self-preservation flag in replica documentation

src/main/webapp/app/registry/encryption/encryption.service.ts, webpack/webpack.dev.js
Fix #434 by setting `responseType` to `text`, otherwise it fails when trying to parse the simple string as JSON.
Typescript complains when the response is typed and responseType is `text`, so I removed `<string>` from the service methods.  Related StackOverflow: https://stackoverflow.com/q/49771603/3737815
Also added `/config` to the webpack paths so the request can be tested in the `dev` profile.
Related links:
https://angular.io/guide/http#requesting-non-json-data
=> fix encrypt response parsing

.github/dependabot.yml
This adds dependabot.yml file to leverage native support for dependabot through GitHub
Related to https://github.com/jhipster/generator-jhipster/issues/11914
=> Add dependabot.yml file for automatic version upgrades [ci skip]

app.json, system.properties
This updates the Heroku button to start with Java 11 and also use the jhipster_registry version 6.2.0 as default.
Fixes https://github.com/jhipster/jhipster-registry/issues/467
=> Update Heroku deployment to start with Java 11

Dockerfile
On Windows 10 you get an error while building the image: /bin/sh: 1: ./mvnw: not found
Using dos2unix to replace \r\n with \n solves the problem for Windows
=> Update Dockerfile to support building image on Win

.yo-rc.json, package-lock.json, package.json, pom.xml, sonar-project.properties
Related to jhipster/jhipster#906
An important security vulnerabilities was discovered in all versions of Undertow before Undertow 2.2.0.Final. JHipster release v6.10.5 fixes this security vulnerabilities.
https://www.jhipster.tech/2020/11/07/jhipster-release-6.10.5.html
https://nvd.nist.gov/vuln/detail/CVE-2020-10687
=> Update Undertow to fix CVE-2020-10687

app.json
Fixes the Heroku deploy button.
In v6.4.0 it was broken because [the release](https://github.com/jhipster/jhipster-registry/releases/tag/v6.4.0) did not contain a JAR file (related issue https://github.com/jhipster/jhipster-registry/issues/490).
=> align app.json version with latest release

.github/workflows/github-ci.yml, pom.xml
Related with https://github.com/jhipster/generator-jhipster/issues/14304
=> Update Nodejs version to 14.16.0

src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java
This PR allows all users to call /api/account and /api/logout without an admin role. Without these settings, there will be an infinite loop, when using oauth2
Fixes #473
=> allow /api/account and /api/logout for any authenticated users

.github/workflows/publish_docker.yml, package-lock.json, pom.xml, src/main/docker/jib/entrypoint.sh
- Fix jib plugin by creating a target folder (for logs) and changing ownership.
- Add additional arm64 platform.
- Add workflow that publishes both images (arm64/amd64) to GitHub containers.
Related to https://github.com/jhipster/jhipster-registry/issues/500
=> Add arm64 image to docker.

.github/workflows/github-ci.yml, .github/workflows/publish_docker.yml, LICENSE.txt, NOTICE
- related to https://github.com/jhipster/generator-jhipster/issues/17509
=> Update License to 2022
