pom.xml

Use spring-cloud-netflix-eureka-server in pom

---

Dockerfile

Fix https://github.com/jhipster/jhipster-registry/issues/1

Add Dockerfile to build Docker image

---

src/main/resources/config/application.yml

Add some comments and links about eureka.server.* properties to application.yml

Add some comments and links about eureka.server.* properties to application.yml

---

pom.xml

exclude servlet-api 2.5 jar from eureka server dependency

---

Dockerfile

With this the registry becomes fully usable with docker.

add docker environment variables for specifying git config source

---

.yo-rc.json

Update app name so that its in line with jhipster generated apps naming conventions

Update app name so that its in line with jhipster

---

Procfile
README.md
app.json

Enables one-click deploy to Heroku (with limitations described in the README)

Added a Heroku button

---

Procfile
README.md

Added a better header title for Heroku deployment.
Added a default password in the `Procfile` so that the server starts up even if `JHIPSTER_PASSWORD` is not set.

Heroku improvements

---

src/main/webapp/app/ssh/ssh.html

Minor edits for git ssh docs in the registry.
It would be great if we could make an "info" button to show/hide this docs.

correct git ssh setup docs

---

src/main/java/io/github/jhipster/registry/web/rest/EurekaResource.java
src/main/java/io/github/jhipster/registry/web/rest/dto/EurekaDTO.java
src/main/webapp/app/admin/health/health.controller.js
src/main/webapp/app/admin/health/health.html
src/main/webapp/app/admin/health/health.service.js
src/main/webapp/app/applications/applications.controller.js
src/main/webapp/app/applications/applications.html
src/main/webapp/app/components/login/login.controller.js
src/main/webapp/app/components/util/status-label.directive.js
src/main/webapp/app/home/eureka.status.service.js
src/main/webapp/app/home/home.controller.js
src/main/webapp/app/home/home.html
src/main/webapp/app/layouts/navbar/navbar.html
src/main/webapp/index.html
src/test/javascript/spec/app/admin/health/health.controller.spec.js

Add a dashboard overview on home page
@jdubois what do you think?
fix #56

Add dashboard

---

src/main/docker/dev/Dockerfile

fix https://github.com/jhipster/jhipster-registry/issues/64

[develop] consistent dockerfile for development

---

src/main/java/io/github/jhipster/registry/web/rest/ProfileInfoResource.java
src/main/resources/config/application-dev.yml
src/main/webapp/app/config/config.controller.js
src/main/webapp/app/config/config.html
src/main/webapp/app/config/config.service.js
src/main/webapp/app/services/profile.service.js
src/main/webapp/index.html

- Fix for the default dev profile to automatically include config server's "native" profile.
- new features described in issue #49

Config page improvements 

---

gulpfile.js

import fonts from the correct folder

---

Dockerfile
src/main/docker/dev/Dockerfile

Fix https://github.com/jhipster/generator-jhipster/issues/4127

migrate the java docker image from _/java to _/openjdk

---

src/main/webapp/app/shared/pipe/group-by.pipe.ts
src/main/webapp/app/shared/pipe/groupBy.pipe.ts
src/main/webapp/app/shared/routes/route-selector.component.html
src/main/webapp/app/shared/routes/route-selector.component.scss
src/main/webapp/app/shared/routes/route-selector.component.ts
src/main/webapp/app/shared/shared-common.module.ts
src/main/webapp/content/scss/global.scss

Related to #99.
- The dropdown :
- The search box :
All "down" routes are not clickable.
You can search instances by app name with the search box (inside the dropdown).

Dropdown list routes with search box

---

src/main/webapp/app/shared/routes/route-selector.component.html
src/main/webapp/app/shared/routes/route-selector.component.scss
src/main/webapp/app/shared/routes/route-selector.component.ts
src/main/webapp/app/shared/routes/route.model.ts

- Fix bug in Chrome (view cannot update the route button when clicked) 
- Add a darker border to dropdown
- Refactor a little bit the typescript code

(Routes component) Fix view bug in Chrome & polish

---

Procfile
README.md
app.json
pom.xml

* Add the Node.js buildpack to the Heroku app.json
* Updated Heroku Button link in Readme
* Added heroku build profile to clean build artifacts

Update Heroku deployment

---

src/main/webapp/app/registry/config/config.component.html

Fixed #153

---

src/main/webapp/app/layouts/profiles/profile.service.ts
src/main/webapp/app/registry/config/config.component.html
src/main/webapp/app/registry/config/config.component.ts
src/main/webapp/app/registry/config/config.service.ts

the part that is fixed:
---
improved displaying of properties

Improve cloud config screen

---

pom.xml
src/main/java/io/github/jhipster/registry/service/CloudConfigRefreshService.java

k8s and openshift service to identify configMap changes and auto refresh @RefreshScoped beans

k8s configMap auto-refresh

---

src/main/resources/config/bootstrap-prod.yml

Should use prod profile config when in prod

---

pom.xml

Related to this PR https://github.com/jhipster/generator-jhipster/pull/6177
Thanks to @haydar9

[develop] Fix docker build in dev profile

---

.travis.yml

[develop] Travis: sleep to 45 before curling

---

pom.xml

Changed https://github.com/jhipster/jhipster-registry/pull/186 to point at `develop` instead of `master`. Thanks for tips and increasing the waiting-period, @pascalgrimaud !

Jhipster deps

---

src/main/webapp/app/home/home.component.ts
src/main/webapp/app/layouts/navbar/navbar.component.ts

Similar to this commit: https://github.com/jhipster/generator-jhipster/commit/42365267d7d549a1feb1984286f71ac9db8506fb#diff-bdf8b0c8d7a2d958762b7d01b79918a5

[develop] Fix version in navbar, which is not displayed in prod

---

Dockerfile

move target directory creation to second stage of docker build

---

src/main/webapp/index.html

Similar to https://github.com/jhipster/generator-jhipster/commit/b7cf2d4a4cf97f5bb08fc24c5a8c31467f9c8fd7

use relative instead of absolute path for context paths and proxies

---

pom.xml

upgrade yarn and the frontend maven plugin fix #195

---

src/main/resources/config/application.yml

fix #185
This can be brought back the issue is fixed in upstream Springfox.

remove "/config/" path from swagger regex to prevent an issue

---

src/main/resources/config/application-oauth2.yml

OIDC : custom session cookie name

---

src/main/docker/Dockerfile

add JAVA_OPTS to Dockerfile

---

pom.xml

see: https://github.com/jhipster/generator-jhipster/issues/6736

disable auto-proxy in frontend plugin in some cases 

---

Dockerfile
src/main/docker/Dockerfile

1st improvement:
- add JAVA_OPTS to main Dockerfile for Docker Hub
2nd improvement:
- move ADD / COPY to end of Dockerfile
- related to https://github.com/jhipster/generator-jhipster/pull/6744
_____

Improve dockerfile

---

src/main/java/io/github/jhipster/registry/service/ZuulUpdaterService.java

solve refresh status issue in Administration tab

---

src/main/java/io/github/jhipster/registry/config/JWTSecurityConfiguration.java

- [X ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ X] Tests are added where necessary
- [ X] Documentation is added/updated where necessary
- [ X] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

Open /management/health route

---

src/main/webapp/app/admin/configuration/configuration.component.html
src/main/webapp/app/admin/health/health.component.html
src/main/webapp/app/admin/logfile/logfile.component.html
src/main/webapp/app/admin/logs/logs.component.html
src/main/webapp/app/admin/metrics/metrics.component.html
src/main/webapp/app/registry/history/history.component.html
src/main/webapp/app/shared/refresh/refresh-selector.component.html
src/main/webapp/app/shared/routes/route-selector.component.html
src/main/webapp/content/scss/global.scss

- Fix selector with Angular5, which is not always correctly displayed.
- To be consistent, put the selector at right for all pages
_____

[develop] fix route and refresh selector

---

src/main/webapp/app/shared/login/login.component.html

Remove link to register and forgot password in login page
_____

[develop] Remove link to register and forgot password

---

src/main/webapp/app/admin/health/health.service.ts

[develop] fix health page for Spring Boot 1

---

src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.component.ts

No need to press F5 in home page

[develop] Add selector to home page

---

src/main/resources/config/application-oauth2.yml

[develop] fix OAuth2 configuration

---

src/main/java/io/github/jhipster/registry/JHipsterRegistryApp.java

Apply code conventions

---

src/main/webapp/app/home/home.component.ts

[develop] Fix ngOnDestroy for Home Page

---

src/main/java/io/github/jhipster/registry/security/jwt/TokenProvider.java

now it not be able to manage other micro  services.

Matching with other micro service TokenProvider

---

src/main/webapp/app/registry/encryption/encryption.service.ts

Fix encryption screen

---

src/main/java/io/github/jhipster/registry/security/jwt/TokenProvider.java

Reverts jhipster/jhipster-registry#272

Revert "Matching with other micro service TokenProvider"

---

package.json

Related to this: https://github.com/jhipster/jhipster-registry/pull/284#issuecomment-409059180

Upgrade version in package.json: 4.0.0

---

src/main/java/io/github/jhipster/registry/config/Constants.java
src/main/java/io/github/jhipster/registry/config/UaaConfiguration.java
src/main/java/io/github/jhipster/registry/filters/UaaTokenRelayFilter.java
src/main/java/io/github/jhipster/registry/security/oauth2/OAuth2ClientCredentialsService.java
src/main/java/io/github/jhipster/registry/web/rest/RoutesResource.java
src/main/resources/config/application-dev.yml
src/main/resources/config/application-uaa.yaml
src/main/resources/config/application.yml

fix #148 
In order to make this work, make sure the "internal" oauth2 client has the "ROLE_ADMIN":
``` java
clients.inMemory()
.withClient(uaaProperties.getWebClientConfiguration().getClientId())
.secret(passwordEncoder.encode(uaaProperties.getWebClientConfiguration().getSecret()))
.scopes("openid")
.autoApprove(true)
.authorizedGrantTypes("implicit","refresh_token", "password", "authorization_code")
.accessTokenValiditySeconds(accessTokenValidity)
.refreshTokenValiditySeconds(refreshTokenValidity)
.and()
.withClient(jHipsterProperties.getSecurity().getClientAuthorization().getClientId())
.secret(passwordEncoder.encode(jHipsterProperties.getSecurity().getClientAuthorization().getClientSecret()))
.scopes("web-app")
.authorities("ROLE_ADMIN")
.autoApprove(true) …
```

implement client credentials flow for management endpoints to UAA microservices

---

src/main/resources/config/application-uaa.yaml
src/main/resources/config/application.yml

related to discussion at bottom of #278

only fetch registry when using uaa

---

Procfile
app.json

Will hopefully fix or help #295

Optimize default Java and Spring options on Heroku for best boot time

---

src/main/java/io/github/jhipster/registry/filters/responserewriting/SwaggerBasePathRewritingFilter.java
src/test/java/io/github/jhipster/registry/filters/responserewriting/SwaggerBasePathRewritingFilterTest.java

Related to jhipster/generator-jhipster#8328

Fix Swagger UI for Microservices

---

app.json

I'm getting Thymeleaf errors from 4.0.5 on Heroku:
```
2018-10-16T13:13:38.148338+00:00 app[web.1]: 2018-10-16 13:13:38.147  WARN 4 --- [  XNIO-2 task-1] o.s.c.n.zuul.web.ZuulHandlerMapping      : No routes found from RouteLocator
2018-10-16T13:13:38.387564+00:00 app[web.1]: 2018-10-16 13:13:38.387 DEBUG 4 --- [  XNIO-2 task-1] freemarker.cache                         : Couldn't find template in cache for "error.ftl"("en_US", UTF-8
, parsed); will try to load it.
2018-10-16T13:13:38.390461+00:00 app[web.1]: 2018-10-16 13:13:38.390 DEBUG 4 --- [  XNIO-2 task-1] freemarker.cache                         : TemplateLoader.findTemplateSource("error_en_US.ftl"): Not foun
d
2018-10-16T13:13:38.414015+00:00 app[web.1]: 2018-10-16 13:13:38.412 DEBUG 4 --- [  XNIO-2 task-1] freemarker.cache …
```

Rollback to registry version 4.0.4 in app.json

---

app.json

Update default version for Heroku

---

.travis.yml
src/main/java/io/github/jhipster/registry/service/ZuulUpdaterService.java
src/main/java/io/github/jhipster/registry/service/dto/ZuulRouteDTO.java

the sensitive header property must not be null
fix #292

change sensitiveHeaders in ZuulRouteDTO

---

src/main/webapp/app/admin/metrics/metrics.component.html
src/main/webapp/app/admin/metrics/metrics.component.ts

Fix display if metrics component values is empty
related to jhipster/generator-jhipster#9132

fix metrics empty objects

---

pom.xml
src/main/java/io/github/jhipster/registry/config/WebConfigurer.java
src/main/resources/config/application-dev.yml
src/main/resources/config/application-prod.yml
src/main/resources/config/application.yml
src/main/webapp/app/admin/metrics/metrics.component.html
src/main/webapp/app/admin/metrics/metrics.service.ts

Update jhipster dependencies and spring-boot version

---

pom.xml
src/test/java/io/github/jhipster/registry/filters/responserewriting/SwaggerBasePathRewritingFilterTest.java
src/test/java/io/github/jhipster/registry/web/rest/AccountResourceTest.java
src/test/java/io/github/jhipster/registry/web/rest/LogsResourceTest.java
src/test/java/io/github/jhipster/registry/web/rest/SshResourceTest.java
src/test/java/io/github/jhipster/registry/web/rest/UserJWTControllerTest.java
src/test/java/io/github/jhipster/registry/web/rest/errors/CustomParameterizedExceptionTest.java
src/test/java/io/github/jhipster/registry/web/rest/errors/ErrorVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/errors/ExceptionTranslatorTest.java
src/test/java/io/github/jhipster/registry/web/rest/errors/FieldErrorVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/errors/ParameterizedErrorVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/vm/EurekaVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/vm/LoggerVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/vm/LoginVMTest.java
src/test/java/io/github/jhipster/registry/web/rest/vm/UserVMTest.java

Upgrade to JUnit 5

---

src/main/webapp/app/admin/metrics/metrics.service.ts

Metrics: Remove invalid character from uri

---

src/main/java/io/github/jhipster/registry/config/OAuth2SecurityConfiguration.java
src/main/java/io/github/jhipster/registry/web/rest/AccountResource.java

@mraible, this should fix the login issue.

Fix oauth2 login issue

---

pom.xml

@mraible, can you confirm if it solve the issue ? 
Fix #356 

put back io.dropwizard.metrics dependency to enable log reporter

---

README.md

add Azure pipeline badge

---

src/main/webapp/app/admin/logs/logs.component.ts
src/main/webapp/app/admin/logs/logs.service.ts
src/main/webapp/app/shared/routes/route-selector.component.ts
src/main/webapp/app/shared/routes/routes.service.ts

feat: changes loggers for all instance of the same microservice

---

src/main/webapp/app/vendor.ts

[develop] Missing icons

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10173

Update Node version to 10.16.1

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10236

Update Node version to 10.16.3

---

src/main/java/io/github/jhipster/registry/web/rest/ProfileInfoResource.java

Change this condition so that it does not always evaluate to "false"

Update ProfileInforResource - Fixed a Sonar Issue

---

src/main/webapp/app/home/home.component.html
src/main/webapp/app/home/home.scss
src/main/webapp/swagger-ui/index.html

Fix home and swagger pages

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/11048

Update Copywrite Headers for 2020

---

LICENSE.txt
NOTICE

Related to https://github.com/jhipster/generator-jhipster/pull/11048

Update Copyright for 2020

---

azure-pipelines.yml
pom.xml

Related with https://github.com/jhipster/generator-jhipster/pull/11067

Update node to version 12.14.0 LTS

---

.yo-rc.json
pom.xml
src/main/appengine/app.yaml
src/main/resources/config/application-prod-gae.yml
src/main/resources/config/application.yml

This adds a sample configuration for jhipster-registry so that it could easily be deployed to GAE
Fixes https://github.com/jhipster/jhipster-registry/issues/400
Related to https://github.com/jhipster/generator-jhipster/issues/10345

Add Sample Setup for jhipser-registry Deployment

---

src/main/java/io/github/jhipster/registry/config/WebConfigurer.java

Fix invalid CORS request for /config/encrypt

---

src/main/webapp/app/admin/admin-routing.module.ts
src/main/webapp/app/layouts/navbar/navbar.component.html

Links for logs and loggers are incorrect

---

src/main/java/io/github/jhipster/registry/config/info/CloudConfigInfoContributor.java
src/main/webapp/app/layouts/profiles/profile-info.model.ts
src/main/webapp/app/layouts/profiles/profile.service.ts
src/main/webapp/app/registry/config/config.component.ts

display configured config label

---

src/main/resources/config/bootstrap-prod.yml

Add private github repo configuration example.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md
src/main/resources/config/bootstrap-prod.yml
src/main/resources/config/bootstrap.yml
src/main/webapp/app/registry/config/config.component.ts
src/main/webapp/index.html

Related to https://github.com/jhipster/generator-jhipster/issues/11935

Change default branch from master to main

---

Dockerfile

Related to https://github.com/jhipster/generator-jhipster/issues/12665
_____

Add possibility to start slowly the JHipster Registry with Docker

---

.github/workflows/docker.yml
.github/workflows/github-ci.yml
package-lock.json

GitHub Actions

---

app.json

Update version to match current in app.json

---

src/main/webapp/app/blocks/interceptor/auth-expired.interceptor.ts

Fix https://github.com/jhipster/jhipster-registry/issues/439

Remove auto redirect on 401 to fix infinite loop with OAuth2

---

.gitignore
README.md
pom.xml
src/main/docker/vault-config/config/config.hcl
src/main/docker/vault.yml
src/main/resources/config/bootstrap-prod.yml
src/main/resources/config/bootstrap.yml

feat: Integrate Vault backend

---

README.md
package.json
pom.xml
src/main/jib/entrypoint.sh

Patch documentation v7

---

.mvn/wrapper/maven-wrapper.properties

Update maven wrapper version to 3.8.2

---

src/main/java/tech/jhipster/registry/security/jwt/TokenProvider.java
src/main/java/tech/jhipster/registry/security/oauth2/JwtGrantedAuthorityConverter.java
src/main/java/tech/jhipster/registry/web/rest/UserJWTController.java

Change the JWT base64-secret like optional property in oauth2 profile

---

src/main/java/tech/jhipster/registry/config/WebConfigurer.java
src/main/java/tech/jhipster/registry/security/SecurityUtils.java
src/main/java/tech/jhipster/registry/service/CloudConfigRefreshService.java

Refactor - Remove unused imports, use method reference, reordering modifiers

---

.github/workflows/github-ci.yml
.github/workflows/publish_docker.yml

Update workflow scripts

---

.github/workflows/copyright-update.yml

Add script to update copyright
